VueComponent {
	_uid: 0,
	_isVue: true,
	$options: Object {
		components: Object {},
		directives: Object {},
		filters: Object {},
		_base: function Vue(options) { ...
		},
		name: 'HelloWorld',
		data: function mergedInstanceDataFn() { ...
		},
		mounted: [...],
		methods: Object {
			changeText: ...,
			aa: ...
		},
		render: function() { ...
		},
		staticRenderFns: [..., ...],
		_compiled: true,
		_scopeId: 'data-v-469af010',
		beforeCreate: [...],
		__file: 'src/components/HelloWorld.vue',
		_Ctor: Object {
			0: ...
		}
	},
	_renderProxy: VueComponent {
		_uid: 0,
		_isVue: true,
		$options: Object {
			components: ...,
			directives: ...,
			filters: ...,
			_base: ...,
			name: ...,
			data: ...,
			mounted: ...,
			methods: ...,
			render: ...,
			staticRenderFns: ...,
			_compiled: ...,
			_scopeId: ...,
			beforeCreate: ...,
			__file: ...,
			_Ctor: ...
		},
		_renderProxy: VueComponent {
			_uid: ...,
			_isVue: ...,
			$options: ...,
			_renderProxy: ...,
			_self: ...,
			$parent: ...,
			$root: ...,
			$children: ...,
			$refs: ...,
			_watcher: ...,
			_inactive: ...,
			_directInactive: ...,
			_isMounted: ...,
			_isDestroyed: ...,
			_isBeingDestroyed: ...,
			_events: ...,
			_hasHookEvent: ...,
			_vnode: ...,
			_staticTrees: ...,
			$vnode: ...,
			$slots: ...,
			$scopedSlots: ...,
			_c: ...,
			$createElement: ...,
			$attrs: ...,
			$listeners: ...,
			_watchers: ...,
			changeText: ...,
			aa: ...,
			_data: ...,
			title: ...,
			bgText: ...,
			msg: ...,
			$el: ...,
			a: ...
		},
		_self: VueComponent {
			_uid: ...,
			_isVue: ...,
			$options: ...,
			_renderProxy: ...,
			_self: ...,
			$parent: ...,
			$root: ...,
			$children: ...,
			$refs: ...,
			_watcher: ...,
			_inactive: ...,
			_directInactive: ...,
			_isMounted: ...,
			_isDestroyed: ...,
			_isBeingDestroyed: ...,
			_events: ...,
			_hasHookEvent: ...,
			_vnode: ...,
			_staticTrees: ...,
			$vnode: ...,
			$slots: ...,
			$scopedSlots: ...,
			_c: ...,
			$createElement: ...,
			$attrs: ...,
			$listeners: ...,
			_watchers: ...,
			changeText: ...,
			aa: ...,
			_data: ...,
			title: ...,
			bgText: ...,
			msg: ...,
			$el: ...,
			a: ...
		},
		$parent: undefined,
		$root: VueComponent {
			_uid: ...,
			_isVue: ...,
			$options: ...,
			_renderProxy: ...,
			_self: ...,
			$parent: ...,
			$root: ...,
			$children: ...,
			$refs: ...,
			_watcher: ...,
			_inactive: ...,
			_directInactive: ...,
			_isMounted: ...,
			_isDestroyed: ...,
			_isBeingDestroyed: ...,
			_events: ...,
			_hasHookEvent: ...,
			_vnode: ...,
			_staticTrees: ...,
			$vnode: ...,
			$slots: ...,
			$scopedSlots: ...,
			_c: ...,
			$createElement: ...,
			$attrs: ...,
			$listeners: ...,
			_watchers: ...,
			changeText: ...,
			aa: ...,
			_data: ...,
			title: ...,
			bgText: ...,
			msg: ...,
			$el: ...,
			a: ...
		},
		$children: [...],
		$refs: Object {},
		_watcher: Watcher {
			vm: ...,
			deep: ...,
			user: ...,
			lazy: ...,
			sync: ...,
			before: ...,
			cb: ...,
			id: ...,
			active: ...,
			dirty: ...,
			deps: ...,
			newDeps: ...,
			depIds: ...,
			newDepIds: ...,
			expression: ...,
			getter: ...,
			value: ...
		},
		_inactive: null,
		_directInactive: false,
		_isMounted: true,
		_isDestroyed: false,
		_isBeingDestroyed: false,
		_events: Object {},
		_hasHookEvent: false,
		_vnode: VNode {
			tag: ...,
			data: ...,
			children: ...,
			text: ...,
			elm: ...,
			ns: ...,
			context: ...,
			fnContext: ...,
			fnOptions: ...,
			fnScopeId: ...,
			key: ...,
			componentOptions: ...,
			componentInstance: ...,
			parent: ...,
			raw: ...,
			isStatic: ...,
			isRootInsert: ...,
			isComment: ...,
			isCloned: ...,
			isOnce: ...,
			asyncFactory: ...,
			asyncMeta: ...,
			isAsyncPlaceholder: ...
		},
		_staticTrees: [..., ...],
		$vnode: undefined,
		$slots: Object {},
		$scopedSlots: Object {},
		_c: function(a, b, c, d) { ...
		},
		$createElement: function(a, b, c, d) { ...
		},
		$attrs: Object {},
		$listeners: Object {},
		_watchers: [...],
		changeText: function changeText() { ...
		},
		aa: function aa() { ...
		},
		_data: Object {
			msg: ...,
			bgText: ...,
			title: ...
		},
		title: 'HELLOW',
		bgText: 'DEVELOPMENT',
		msg: 'Welcome to Your Vue.js App',
		$el: < div data - v - 469 af010 = ""
		class = "hello" > < h1 data - v - 469 af010 = ""
		class = "ignore" > Welcome to Your Vue.js App < /h1> <h2 data-v-469af010="" class="text-blue">Essential Links</h
		2 > < div data - v - 469 af010 = ""
		class = "title" > < div data - v - 6 f792258 = ""
		data - v - 469 af010 = ""
		class = "cephalosome" > < div data - v - 6 f792258 = ""
		class = "content" > < h1 data - v - 6 f792258 = ""
		class = "text-xxxxl" > DEVELOPMENT < /h1> <h2 data-v-6f792258="" class="text-xxxl text-gray">HELLOW</h
		2 > < p data - v - 6 f792258 = ""
		class = "text-s text-remark has-remark" > < /p></div > < /div></div > < ul data - v - 469 af010 = "" > < li data - v - 469 af010 = ""
		ui - mode = "230"
		class = "example" > < a data - v - 469 af010 = ""
		href = "https://vuejs.org"
		target = "_blank"
		class = "core" > Core Docs < /a></li > < li data - v - 469 af010 = ""
		class = "border" > < a data - v - 469 af010 = ""
		href = "https://forum.vuejs.org"
		target = "_blank"
		class = "text-black" > Forum < /a></li > < /ul> <div data-v-469af010="" class="btn"><button data-v-469af010="">切换</button > < /div> <div data-v-469af010="" class="aspectratio"><div data-v-469af010="" class="aspectratio-content"></div > < div data - v - 469 af010 = ""
		class = "dv" > < span data - v - 469 af010 = ""
		class = "dv-span" > span < /span></div > < /div></div > ,
		a: 1
	},
	_self: VueComponent {
		_uid: 0,
		_isVue: true,
		$options: Object {
			components: ...,
			directives: ...,
			filters: ...,
			_base: ...,
			name: ...,
			data: ...,
			mounted: ...,
			methods: ...,
			render: ...,
			staticRenderFns: ...,
			_compiled: ...,
			_scopeId: ...,
			beforeCreate: ...,
			__file: ...,
			_Ctor: ...
		},
		_renderProxy: VueComponent {
			_uid: ...,
			_isVue: ...,
			$options: ...,
			_renderProxy: ...,
			_self: ...,
			$parent: ...,
			$root: ...,
			$children: ...,
			$refs: ...,
			_watcher: ...,
			_inactive: ...,
			_directInactive: ...,
			_isMounted: ...,
			_isDestroyed: ...,
			_isBeingDestroyed: ...,
			_events: ...,
			_hasHookEvent: ...,
			_vnode: ...,
			_staticTrees: ...,
			$vnode: ...,
			$slots: ...,
			$scopedSlots: ...,
			_c: ...,
			$createElement: ...,
			$attrs: ...,
			$listeners: ...,
			_watchers: ...,
			changeText: ...,
			aa: ...,
			_data: ...,
			title: ...,
			bgText: ...,
			msg: ...,
			$el: ...,
			a: ...
		},
		_self: VueComponent {
			_uid: ...,
			_isVue: ...,
			$options: ...,
			_renderProxy: ...,
			_self: ...,
			$parent: ...,
			$root: ...,
			$children: ...,
			$refs: ...,
			_watcher: ...,
			_inactive: ...,
			_directInactive: ...,
			_isMounted: ...,
			_isDestroyed: ...,
			_isBeingDestroyed: ...,
			_events: ...,
			_hasHookEvent: ...,
			_vnode: ...,
			_staticTrees: ...,
			$vnode: ...,
			$slots: ...,
			$scopedSlots: ...,
			_c: ...,
			$createElement: ...,
			$attrs: ...,
			$listeners: ...,
			_watchers: ...,
			changeText: ...,
			aa: ...,
			_data: ...,
			title: ...,
			bgText: ...,
			msg: ...,
			$el: ...,
			a: ...
		},
		$parent: undefined,
		$root: VueComponent {
			_uid: ...,
			_isVue: ...,
			$options: ...,
			_renderProxy: ...,
			_self: ...,
			$parent: ...,
			$root: ...,
			$children: ...,
			$refs: ...,
			_watcher: ...,
			_inactive: ...,
			_directInactive: ...,
			_isMounted: ...,
			_isDestroyed: ...,
			_isBeingDestroyed: ...,
			_events: ...,
			_hasHookEvent: ...,
			_vnode: ...,
			_staticTrees: ...,
			$vnode: ...,
			$slots: ...,
			$scopedSlots: ...,
			_c: ...,
			$createElement: ...,
			$attrs: ...,
			$listeners: ...,
			_watchers: ...,
			changeText: ...,
			aa: ...,
			_data: ...,
			title: ...,
			bgText: ...,
			msg: ...,
			$el: ...,
			a: ...
		},
		$children: [...],
		$refs: Object {},
		_watcher: Watcher {
			vm: ...,
			deep: ...,
			user: ...,
			lazy: ...,
			sync: ...,
			before: ...,
			cb: ...,
			id: ...,
			active: ...,
			dirty: ...,
			deps: ...,
			newDeps: ...,
			depIds: ...,
			newDepIds: ...,
			expression: ...,
			getter: ...,
			value: ...
		},
		_inactive: null,
		_directInactive: false,
		_isMounted: true,
		_isDestroyed: false,
		_isBeingDestroyed: false,
		_events: Object {},
		_hasHookEvent: false,
		_vnode: VNode {
			tag: ...,
			data: ...,
			children: ...,
			text: ...,
			elm: ...,
			ns: ...,
			context: ...,
			fnContext: ...,
			fnOptions: ...,
			fnScopeId: ...,
			key: ...,
			componentOptions: ...,
			componentInstance: ...,
			parent: ...,
			raw: ...,
			isStatic: ...,
			isRootInsert: ...,
			isComment: ...,
			isCloned: ...,
			isOnce: ...,
			asyncFactory: ...,
			asyncMeta: ...,
			isAsyncPlaceholder: ...
		},
		_staticTrees: [..., ...],
		$vnode: undefined,
		$slots: Object {},
		$scopedSlots: Object {},
		_c: function(a, b, c, d) { ...
		},
		$createElement: function(a, b, c, d) { ...
		},
		$attrs: Object {},
		$listeners: Object {},
		_watchers: [...],
		changeText: function changeText() { ...
		},
		aa: function aa() { ...
		},
		_data: Object {
			msg: ...,
			bgText: ...,
			title: ...
		},
		title: 'HELLOW',
		bgText: 'DEVELOPMENT',
		msg: 'Welcome to Your Vue.js App',
		$el: < div data - v - 469 af010 = ""
		class = "hello" > < h1 data - v - 469 af010 = ""
		class = "ignore" > Welcome to Your Vue.js App < /h1> <h2 data-v-469af010="" class="text-blue">Essential Links</h
		2 > < div data - v - 469 af010 = ""
		class = "title" > < div data - v - 6 f792258 = ""
		data - v - 469 af010 = ""
		class = "cephalosome" > < div data - v - 6 f792258 = ""
		class = "content" > < h1 data - v - 6 f792258 = ""
		class = "text-xxxxl" > DEVELOPMENT < /h1> <h2 data-v-6f792258="" class="text-xxxl text-gray">HELLOW</h
		2 > < p data - v - 6 f792258 = ""
		class = "text-s text-remark has-remark" > < /p></div > < /div></div > < ul data - v - 469 af010 = "" > < li data - v - 469 af010 = ""
		ui - mode = "230"
		class = "example" > < a data - v - 469 af010 = ""
		href = "https://vuejs.org"
		target = "_blank"
		class = "core" > Core Docs < /a></li > < li data - v - 469 af010 = ""
		class = "border" > < a data - v - 469 af010 = ""
		href = "https://forum.vuejs.org"
		target = "_blank"
		class = "text-black" > Forum < /a></li > < /ul> <div data-v-469af010="" class="btn"><button data-v-469af010="">切换</button > < /div> <div data-v-469af010="" class="aspectratio"><div data-v-469af010="" class="aspectratio-content"></div > < div data - v - 469 af010 = ""
		class = "dv" > < span data - v - 469 af010 = ""
		class = "dv-span" > span < /span></div > < /div></div > ,
		a: 1
	},
	$parent: undefined,
	$root: VueComponent {
		_uid: 0,
		_isVue: true,
		$options: Object {
			components: ...,
			directives: ...,
			filters: ...,
			_base: ...,
			name: ...,
			data: ...,
			mounted: ...,
			methods: ...,
			render: ...,
			staticRenderFns: ...,
			_compiled: ...,
			_scopeId: ...,
			beforeCreate: ...,
			__file: ...,
			_Ctor: ...
		},
		_renderProxy: VueComponent {
			_uid: ...,
			_isVue: ...,
			$options: ...,
			_renderProxy: ...,
			_self: ...,
			$parent: ...,
			$root: ...,
			$children: ...,
			$refs: ...,
			_watcher: ...,
			_inactive: ...,
			_directInactive: ...,
			_isMounted: ...,
			_isDestroyed: ...,
			_isBeingDestroyed: ...,
			_events: ...,
			_hasHookEvent: ...,
			_vnode: ...,
			_staticTrees: ...,
			$vnode: ...,
			$slots: ...,
			$scopedSlots: ...,
			_c: ...,
			$createElement: ...,
			$attrs: ...,
			$listeners: ...,
			_watchers: ...,
			changeText: ...,
			aa: ...,
			_data: ...,
			title: ...,
			bgText: ...,
			msg: ...,
			$el: ...,
			a: ...
		},
		_self: VueComponent {
			_uid: ...,
			_isVue: ...,
			$options: ...,
			_renderProxy: ...,
			_self: ...,
			$parent: ...,
			$root: ...,
			$children: ...,
			$refs: ...,
			_watcher: ...,
			_inactive: ...,
			_directInactive: ...,
			_isMounted: ...,
			_isDestroyed: ...,
			_isBeingDestroyed: ...,
			_events: ...,
			_hasHookEvent: ...,
			_vnode: ...,
			_staticTrees: ...,
			$vnode: ...,
			$slots: ...,
			$scopedSlots: ...,
			_c: ...,
			$createElement: ...,
			$attrs: ...,
			$listeners: ...,
			_watchers: ...,
			changeText: ...,
			aa: ...,
			_data: ...,
			title: ...,
			bgText: ...,
			msg: ...,
			$el: ...,
			a: ...
		},
		$parent: undefined,
		$root: VueComponent {
			_uid: ...,
			_isVue: ...,
			$options: ...,
			_renderProxy: ...,
			_self: ...,
			$parent: ...,
			$root: ...,
			$children: ...,
			$refs: ...,
			_watcher: ...,
			_inactive: ...,
			_directInactive: ...,
			_isMounted: ...,
			_isDestroyed: ...,
			_isBeingDestroyed: ...,
			_events: ...,
			_hasHookEvent: ...,
			_vnode: ...,
			_staticTrees: ...,
			$vnode: ...,
			$slots: ...,
			$scopedSlots: ...,
			_c: ...,
			$createElement: ...,
			$attrs: ...,
			$listeners: ...,
			_watchers: ...,
			changeText: ...,
			aa: ...,
			_data: ...,
			title: ...,
			bgText: ...,
			msg: ...,
			$el: ...,
			a: ...
		},
		$children: [...],
		$refs: Object {},
		_watcher: Watcher {
			vm: ...,
			deep: ...,
			user: ...,
			lazy: ...,
			sync: ...,
			before: ...,
			cb: ...,
			id: ...,
			active: ...,
			dirty: ...,
			deps: ...,
			newDeps: ...,
			depIds: ...,
			newDepIds: ...,
			expression: ...,
			getter: ...,
			value: ...
		},
		_inactive: null,
		_directInactive: false,
		_isMounted: true,
		_isDestroyed: false,
		_isBeingDestroyed: false,
		_events: Object {},
		_hasHookEvent: false,
		_vnode: VNode {
			tag: ...,
			data: ...,
			children: ...,
			text: ...,
			elm: ...,
			ns: ...,
			context: ...,
			fnContext: ...,
			fnOptions: ...,
			fnScopeId: ...,
			key: ...,
			componentOptions: ...,
			componentInstance: ...,
			parent: ...,
			raw: ...,
			isStatic: ...,
			isRootInsert: ...,
			isComment: ...,
			isCloned: ...,
			isOnce: ...,
			asyncFactory: ...,
			asyncMeta: ...,
			isAsyncPlaceholder: ...
		},
		_staticTrees: [..., ...],
		$vnode: undefined,
		$slots: Object {},
		$scopedSlots: Object {},
		_c: function(a, b, c, d) { ...
		},
		$createElement: function(a, b, c, d) { ...
		},
		$attrs: Object {},
		$listeners: Object {},
		_watchers: [...],
		changeText: function changeText() { ...
		},
		aa: function aa() { ...
		},
		_data: Object {
			msg: ...,
			bgText: ...,
			title: ...
		},
		title: 'HELLOW',
		bgText: 'DEVELOPMENT',
		msg: 'Welcome to Your Vue.js App',
		$el: < div data - v - 469 af010 = ""
		class = "hello" > < h1 data - v - 469 af010 = ""
		class = "ignore" > Welcome to Your Vue.js App < /h1> <h2 data-v-469af010="" class="text-blue">Essential Links</h
		2 > < div data - v - 469 af010 = ""
		class = "title" > < div data - v - 6 f792258 = ""
		data - v - 469 af010 = ""
		class = "cephalosome" > < div data - v - 6 f792258 = ""
		class = "content" > < h1 data - v - 6 f792258 = ""
		class = "text-xxxxl" > DEVELOPMENT < /h1> <h2 data-v-6f792258="" class="text-xxxl text-gray">HELLOW</h
		2 > < p data - v - 6 f792258 = ""
		class = "text-s text-remark has-remark" > < /p></div > < /div></div > < ul data - v - 469 af010 = "" > < li data - v - 469 af010 = ""
		ui - mode = "230"
		class = "example" > < a data - v - 469 af010 = ""
		href = "https://vuejs.org"
		target = "_blank"
		class = "core" > Core Docs < /a></li > < li data - v - 469 af010 = ""
		class = "border" > < a data - v - 469 af010 = ""
		href = "https://forum.vuejs.org"
		target = "_blank"
		class = "text-black" > Forum < /a></li > < /ul> <div data-v-469af010="" class="btn"><button data-v-469af010="">切换</button > < /div> <div data-v-469af010="" class="aspectratio"><div data-v-469af010="" class="aspectratio-content"></div > < div data - v - 469 af010 = ""
		class = "dv" > < span data - v - 469 af010 = ""
		class = "dv-span" > span < /span></div > < /div></div > ,
		a: 1
	},
	$children: [VueComponent {
		_uid: ...,
		_isVue: ...,
		$options: ...,
		_renderProxy: ...,
		_self: ...,
		$parent: ...,
		$root: ...,
		$children: ...,
		$refs: ...,
		_watcher: ...,
		_inactive: ...,
		_directInactive: ...,
		_isMounted: ...,
		_isDestroyed: ...,
		_isBeingDestroyed: ...,
		_events: ...,
		_hasHookEvent: ...,
		_vnode: ...,
		_staticTrees: ...,
		$vnode: ...,
		$slots: ...,
		$scopedSlots: ...,
		_c: ...,
		$createElement: ...,
		$attrs: ...,
		$listeners: ...,
		_watchers: ...,
		_props: ...,
		_data: ...,
		$el: ...
	}],
	$refs: Object {},
	_watcher: Watcher {
		vm: VueComponent {
			_uid: ...,
			_isVue: ...,
			$options: ...,
			_renderProxy: ...,
			_self: ...,
			$parent: ...,
			$root: ...,
			$children: ...,
			$refs: ...,
			_watcher: ...,
			_inactive: ...,
			_directInactive: ...,
			_isMounted: ...,
			_isDestroyed: ...,
			_isBeingDestroyed: ...,
			_events: ...,
			_hasHookEvent: ...,
			_vnode: ...,
			_staticTrees: ...,
			$vnode: ...,
			$slots: ...,
			$scopedSlots: ...,
			_c: ...,
			$createElement: ...,
			$attrs: ...,
			$listeners: ...,
			_watchers: ...,
			changeText: ...,
			aa: ...,
			_data: ...,
			title: ...,
			bgText: ...,
			msg: ...,
			$el: ...,
			a: ...
		},
		deep: false,
		user: false,
		lazy: false,
		sync: false,
		before: function before() { ...
		},
		cb: function noop(a, b, c) { ...
		},
		id: 1,
		active: true,
		dirty: false,
		deps: [..., ..., ...],
		newDeps: [],
		depIds: Set {
			set: ...
		},
		newDepIds: Set {
			set: ...
		},
		expression: 'function () {
		vm._update(vm._render(), hydrating);
	}
	', getter: function () { ... }, value: undefined}, _inactive: null, _directInactive: false, _isMounted: true, _isDestroyed: false, _isBeingDestroyed: false, _events: Object{}, _hasHookEvent: false, _vnode: VNode{tag: '
	div ', data: Object{staticClass: ...}, children: [..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ...], text: undefined, elm: <div data-v-469af010="" class="hello"><h1 data-v-469af010="" class="ignore">Welcome to Your Vue.js App</h1> <h2 data-v-469af010="" class="text-blue">Essential Links</h2> <div data-v-469af010="" class="title"><div data-v-6f792258="" data-v-469af010="" class="cephalosome"><div data-v-6f792258="" class="content"><h1 data-v-6f792258="" class="text-xxxxl">DEVELOPMENT</h1> <h2 data-v-6f792258="" class="text-xxxl text-gray">HELLOW</h2> <p data-v-6f792258="" class="text-s text-remark has-remark"></p></div></div></div> <ul data-v-469af010=""><li data-v-469af010="" ui-mode="230" class="example"><a data-v-469af010="" href="https://vuejs.org" target="_blank" class="core"> Core Docs </a></li> <li data-v-469af010="" class="border"><a data-v-469af010="" href="https://forum.vuejs.org" target="_blank" class="text-black"> Forum </a></li></ul> <div data-v-469af010="" class="btn"><button data-v-469af010="">切换</button></div> <div data-v-469af010="" class="aspectratio"><div data-v-469af010="" class="aspectratio-content"></div> <div data-v-469af010="" class="dv"><span data-v-469af010="" class="dv-span">span</span></div></div></div>, ns: undefined, context: VueComponent{_uid: ..., _isVue: ..., $options: ..., _renderProxy: ..., _self: ..., $parent: ..., $root: ..., $children: ..., $refs: ..., _watcher: ..., _inactive: ..., _directInactive: ..., _isMounted: ..., _isDestroyed: ..., _isBeingDestroyed: ..., _events: ..., _hasHookEvent: ..., _vnode: ..., _staticTrees: ..., $vnode: ..., $slots: ..., $scopedSlots: ..., _c: ..., $createElement: ..., $attrs: ..., $listeners: ..., _watchers: ..., changeText: ..., aa: ..., _data: ..., title: ..., bgText: ..., msg: ..., $el: ..., a: ...}, fnContext: undefined, fnOptions: undefined, fnScopeId: undefined, key: undefined, componentOptions: undefined, componentInstance: undefined, parent: undefined, raw: false, isStatic: false, isRootInsert: true, isComment: false, isCloned: false, isOnce: false, asyncFactory: undefined, asyncMeta: undefined, isAsyncPlaceholder: false}, _staticTrees: [VNode{tag: ..., data: ..., children: ..., text: ..., elm: ..., ns: ..., context: ..., fnContext: ..., fnOptions: ..., fnScopeId: ..., key: ..., componentOptions: ..., componentInstance: ..., parent: ..., raw: ..., isStatic: ..., isRootInsert: ..., isComment: ..., isCloned: ..., isOnce: ..., asyncFactory: ..., asyncMeta: ..., isAsyncPlaceholder: ...}, VNode{tag: ..., data: ..., children: ..., text: ..., elm: ..., ns: ..., context: ..., fnContext: ..., fnOptions: ..., fnScopeId: ..., key: ..., componentOptions: ..., componentInstance: ..., parent: ..., raw: ..., isStatic: ..., isRootInsert: ..., isComment: ..., isCloned: ..., isOnce: ..., asyncFactory: ..., asyncMeta: ..., isAsyncPlaceholder: ...}], $vnode: undefined, $slots: Object{}, $scopedSlots: Object{}, _c: function (a, b, c, d) { ... }, $createElement: function (a, b, c, d) { ... }, $attrs: Object{}, $listeners: Object{}, _watchers: [Watcher{vm: ..., deep: ..., user: ..., lazy: ..., sync: ..., before: ..., cb: ..., id: ..., active: ..., dirty: ..., deps: ..., newDeps: ..., depIds: ..., newDepIds: ..., expression: ..., getter: ..., value: ...}], changeText: function changeText() { ... }, aa: function aa() { ... }, _data: Object{msg: '
	Welcome to Your Vue.js App ', bgText: '
	DEVELOPMENT ', title: '
	HELLOW '}, title: '
	HELLOW ', bgText: '
	DEVELOPMENT ', msg: '
	Welcome to Your Vue.js App ', $el: <div data-v-469af010="" class="hello"><h1 data-v-469af010="" class="ignore">Welcome to Your Vue.js App</h1> <h2 data-v-469af010="" class="text-blue">Essential Links</h2> <div data-v-469af010="" class="title"><div data-v-6f792258="" data-v-469af010="" class="cephalosome"><div data-v-6f792258="" class="content"><h1 data-v-6f792258="" class="text-xxxxl">DEVELOPMENT</h1> <h2 data-v-6f792258="" class="text-xxxl text-gray">HELLOW</h2> <p data-v-6f792258="" class="text-s text-remark has-remark"></p></div></div></div> <ul data-v-469af010=""><li data-v-469af010="" ui-mode="230" class="example"><a data-v-469af010="" href="https://vuejs.org" target="_blank" class="core"> Core Docs </a></li> <li data-v-469af010="" class="border"><a data-v-469af010="" href="https://forum.vuejs.org" target="_blank" class="text-black"> Forum </a></li></ul> <div data-v-469af010="" class="btn"><button data-v-469af010="">切换</button></div> <div data-v-469af010="" class="aspectratio"><div data-v-469af010="" class="aspectratio-content"></div> <div data-v-469af010="" class="dv"><span data-v-469af010="" class="dv-span">span</span></div></div></div>, a: 1}